# These are supported funding model platforms
liberapay: hantsy # Replace with a single Liberapay username
issuehunt: hantsy # Replace with a single IssueHunt username
custom: ['https://www.buymeacoffee.com/hantsy'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
