spring.application.name=demo
logging.level.com.example=DEBUG
logging.level.org.springframework.boot.elasticsearch=DEBUG
logging.level.com.datastax.driver=DEBUG

spring.cassandra.keyspace-name=demo
spring.cassandra.schema-action=recreate