name: spring-reactive-boot-reactor-kafka

on:
  push:
    paths:
      - "boot-reactor-kafka/**"
    branches: [ master ]
  pull_request:
    paths:
      - "boot-reactor-kafka/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Sender with Maven
      run: |
        cd boot-reactor-kafka/sender
        mvn -B package --file pom.xml
    - name: Build Receiver with Maven
      run: |
        cd boot-reactor-kafka/receiver
        mvn -B package --file pom.xml
