name: spring-reactive-boot-data-mongo

on:
  push:
    paths:
      - "boot-data-mongo/**"
    branches: [ master ]
  pull_request:
    paths:
      - "boot-data-mongo/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd boot-data-mongo
        mvn -B package --file pom.xml
