name: spring-reactive-boot-data-mongo-tailable

on:
  push:
    paths:
      - "boot-data-mongo-tailable/**"
    branches: [ master ]
  pull_request:
    paths:
      - "boot-data-mongo-tailable/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Start up databases via Docker Compose 
      run: |
        docker-compose up -d mongodb
        sleep 5
        docker ps -a      
    - name: Build with Maven
      run: |
        cd boot-data-mongo-tailable
        mvn -B package --file pom.xml
