name: Java CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16' ]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
    
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0


