name: spring-reactive-security-method

on:
  push:
    paths:
      - "security-method/**"
    branches: [ master ]
  pull_request:
    paths:
      - "security-method/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd security-method
        mvn -B package --file pom.xml
