name: spring-reactive-session-data-mongo

on:
  push:
    paths:
      - "session-data-mongo/**"
    branches: [ master ]
  pull_request:
    paths:
      - "session-data-mongo/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Start up databases via Docker Compose 
      run: |
        docker-compose up -d mongodb
        sleep 5
        docker ps -a          
    - name: Build with Maven
      run: |
        cd session-data-mongo
        mvn -B package --file pom.xml
