name: spring-reactive-session

on:
  push:
    paths:
      - "session/**"
    branches: [ master ]
  pull_request:
    paths:
      - "session/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd session
        mvn -B package --file pom.xml
