name: spring-reactive-war

on:
  push:
    paths:
      - "war/**"
    branches: [ master ]
  pull_request:
    paths:
      - "war/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd war
        mvn -B clean verify --file pom.xml -Pintegration
